# Generated by Django 3.1.14 on 2023-11-07 08:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('script_type', models.CharField(max_length=1)),
                ('year', models.IntegerField()),
                ('season', models.IntegerField(null=True)),
                ('episode', models.TextField(null=True)),
                ('episode_title', models.TextField(null=True)),
                ('script_content', models.TextField()),
                ('genre_text', models.JSONField(null=True)),
                ('category', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('search_content', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('network', models.JSONField(null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScriptMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('script_type', models.CharField(max_length=1)),
                ('year_text', models.TextField()),
                ('season_text', models.TextField(null=True)),
                ('episode_text', models.TextField(null=True)),
                ('episode_title', models.TextField(null=True)),
                ('script_content', models.TextField()),
                ('genre_text', models.JSONField(null=True)),
                ('category', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('network', models.JSONField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='script',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['year'], name='search_V2_s_year_c19bbc_btree'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['script_type'], name='search_V2_s_script__b2866a_btree'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_content'], name='search_V2_s_search__a2fa46_gin'),
        ),
    ]
