branch-defaults:
  default:
    environment: usc-script-database-web-dev-v2
environment-defaults:
  usc-script-database-web-dev-v2:
    branch: null
    repository: null
global:
  application_name: usc-script-database-web-prod
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: aws-elasticbeanstalk-ec2-role
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
