branch-defaults:
  default:
    environment: Nlcserver2025-env
environment-defaults:
  Nlcserver2025-env:
    branch: null
    repository: null
  usc-script-database-web-dev-v2:
    branch: null
    repository: null
  usc-script-database-web-prod:
    branch: null
    repository: null
global:
  application_name: nlc_server_2025
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
