branch-defaults:
  default:
    environment: usc-script-database-web-prod
environment-defaults:
  usc-script-database-web-prod:
    branch: null
    repository: null
global:
  application_name: usc-script-database-web-prod
  default_ec2_keyname: aws-eb
  default_platform: Python 3.6
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-prod
  sc: null
  workspace_type: Application
